### ISSUE TITLE
Failed to extract.

### ISSUE THREAD

**Issue by skittlesvampir** [sailfish-on-davinci/issues#13]
When I flash the zip file with twrp I get error 7 and that a mount point is busy. When I unmount everything I only get "failed to extract".
Can you help me?

**Comment by 0312birdzhang** [comment]
all you need is retry, don’t know it’s a bug of twrp or the zip file

skittlesvampir <notifications@github.com>于2020年6月26日 周五01:51写道：

**Comment by skittlesvampir** [comment]
What TWRP so you use? Can you send  send me a link to one that worked for you after a few tries?
Is unmounting necessary?

**Comment by 0312birdzhang** [comment]
https://twrp.me/davinci the official version
Forget mount or unmount, what you need is just press back button and
reselect sailfishos zip file when failed. JUST RETRY!

skittlesvampir <notifications@github.com>于2020年6月26日 周五13:44写道：

**Comment by skittlesvampir** [comment]
How did you flash lineage? Yesterday the installation worked fine but today I always get an error that Miui firmware is missing when flashing the lineage you linked in the xda thread.

**Comment by 0312birdzhang** [comment]
If you are not on android 9 base rom, then you need flash android 9
firmware first. Did you format data partition?

skittlesvampir <notifications@github.com>于2020年6月26日 周五17:32写道：

**Comment by skittlesvampir** [comment]
I formatted everything, flashed android 9 firmware and lineageos worked.
I rebooted back to twrp and tried to flash sailfish a dozen times but all failed. Do I really need to try _that many_ time?

**Comment by skittlesvampir** [comment]
Ok. It was the TWRP. I used the newest version ( 3.4.0-0 ) which failed everytime. Version 3.3.1-0 worked at the first try.
Thank you for porting sailfish to davinci! You're awesome!

**Comment by 0312birdzhang** [comment]
Oh, i haven’t try the newest twrp, thank you for the information, i need
update this on xda.

skittlesvampir <notifications@github.com>于2020年6月26日 周五19:57写道：

**Comment by skittlesvampir** [comment]
I saw in your youtube video that you got anbox working. Are there any plans to make that public available?

**Comment by 0312birdzhang** [comment]
it’s dead now and it was working on vince, not davinci.

skittlesvampir <notifications@github.com>于2020年6月26日 周五21:00写道：

**Comment by skittlesvampir** [comment]
So no android apps for davinci?

**Comment by 0312birdzhang** [comment]
No android apps support, Jolla said they will make it on community device
at some time.

skittlesvampir <notifications@github.com>于2020年6月26日 周五21:17写道：
